#!/bin/bash

geth --testnet --rpc --rpcapi db,eth,net,web3,personal,miner --cache=1024 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --datadir  /Volumes/External/Ethereum_project/Blockchain_Networks/Ropsten/
